import { StyleSheet } from 'react-native';

const HomeStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#343a40',
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: 'space-around',
        paddingHorizontal: 40,
        marginTop: 10,
    },
    home: {
        width: '100%',
        alignItems: 'center',
        marginBottom: 20,
    },
    loadingText: {
        fontSize: 24,
        fontFamily: 'Poppins_600SemiBold',
        marginBottom: 20,
        color: '#FFF', 
    },
    currentTime: {
        fontSize: 24,
        fontFamily: 'Poppins_600SemiBold',
        marginBottom: 20,
        color: '#FFF',
    },
    buttonContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        width: '100%',
        marginBottom: 20,
        gap: 20,
    },
    welcomeContainer: {
        display: 'flex',
    },
    welcome: {
        textAlign: 'center',
        color: '#FFF',
        fontSize: 24,
        fontFamily: 'Poppins_600SemiBold',
    },
    name: {
        textAlign: 'center',
        color: '#509e2f',
        fontSize: 24,
        fontFamily: 'Poppins_600SemiBold',
    },
    dateNow: {
        color: '#FFF',
        fontSize: 16,
        fontFamily: 'Poppins_600SemiBold',
        textAlign: 'center',
    },
    button: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
        gap: 5,
        backgroundColor: '#509e2f',
        padding: 15,
        borderRadius: 5,
        marginBottom: -60,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Poppins_600SemiBold',
    },
    status: {
        fontSize: 18,
        fontWeight: '500',
        marginTop: 20,
    },
    gorilla: {
        width: 100,
        height: 100,
        alignSelf: 'center',
        resizeMode: 'contain',
    },
    gps: {
        width: 20,
        height: 20,
        resizeMode: 'contain',
        marginTop: -3,
    },
    comprovantes: {
        color: '#FFF',
        fontSize: 16,
        alignSelf: 'center',
        fontFamily: 'Poppins_500Medium',
    },
    loadingIcon: {
        marginTop: 250,
    },
    workStatus: {
        fontSize: 18,
        color: '#509e2f',
        fontFamily: 'Poppins_500Medium',
        textAlign: 'center',
    },
    workTime: {
        fontSize: 32,
        fontFamily: 'Poppins_500Medium',
        color: '#fff',
        textAlign: 'left',
    },
    progressBar: {
        width: '100%',
        height: 30,
        backgroundColor: '#ddd',
        borderRadius: 20,
        marginVertical: 10,
    },
    progressCircleContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20,
    },
    progressText: {
        fontSize: 16,
        color: '#FFF',
        marginTop: 10,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.459)', // Fundo do modal
    },
    modalContent: {
        width: '80%',
        backgroundColor: '#343a40',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
    },
    modalConfirmationContent: {
        width: '100%',
        height: '90%',
        marginTop: 120,
        backgroundColor: '#343a40',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    modalTitle: {
        fontSize: 18,
        fontFamily: 'Poppins_600SemiBold',
        marginBottom: 20,
        color: '#FFF',
        textAlign: 'center',
    },
    modalTitleTime: {
        fontSize: 28,
        fontFamily: 'Poppins_600SemiBold',
        marginBottom: 20,
        color: '#FFF',
        textAlign: 'center',
    },
    modalSubTitle: {
        fontSize: 16,
        fontFamily: 'Poppins_500Medium',
        marginBottom: 20,
        color: '#FFF', 
        textAlign: 'center',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    buttonCancel: {
        backgroundColor: '#606c77',
        fontFamily: 'Poppins_600SemiBold',
        padding: 10,
        borderRadius: 5,
        width: '48%',
        alignItems: 'center',
    },
    buttonConfirm: {
        fontFamily: 'Poppins_600SemiBold',
        backgroundColor: '#509e2f',
        padding: 10,
        borderRadius: 5,
        width: '48%',
        alignItems: 'center',
    },
    buttonOk: {
        backgroundColor: '#509e2f',
        padding: 10,
        color: '#FFF',
        textAlign: 'center',
        borderRadius: 5,
        minWidth: '48%',
        fontFamily: 'Poppins_600SemiBold',
    },
    buttonOkText: {
        color: 'white',
        fontFamily: 'Poppins_600SemiBold',
        textAlign: 'center',
    },
    titleConfirmRegister: {
        color: '#FFF',
        fontFamily: 'Poppins_600SemiBold',
        textAlign: 'center',
        fontSize: 22,
    },
});

export default HomeStyles;
